[project]
name = "mcp-checkov-chatbot"
version = "0.1.0"
description = "MCP + Checkov + GPT"
requires-python = ">=3.10"

dependencies = [
  "mcp>=1.10.0,<2.0.0",
  "python-dotenv",
  "httpx",
  "openai"
]

[tool.uv]
dev-dependencies = []
